%% 20131222


%% 1643 - Running BOLD-Motion Nuiance Parameter Correlations (No Nuisance Regression from BOLD)
% This was missing during the previous analysis of BOLD-Nuisance correlations. Need to see these results before the
% publication goes out

% Setup correlation parameters
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-Motion',...
        'Relation', 'Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', [],...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', [],...
        'MaskThreshold', [],...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData);
meanCorrData = mean(corrData);
store(meanCorrData);
brainData = plot(meanCorrData, 'CLim', [-3 3]);
store(brainData, 'ext', {'fig', 'png'});