function specStruct = parameters(~)
%PARAMETERS Returns a parameter structure with default values for EEG spectral analysis
%
%   SYNTAX:
%   specStruct = parameters(spectralObj)
%
%   OUTPUT:
%   specStruct:
%
%   INPUT:
%   spectalObj:
%
%   Written by Josh Grooms on 20130910


%% The Spectral Analysis Input Parameter Structure
specStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', [0.01 0.08],...        
        'GSR', true,...
        'ParentData', [],...
        'Scans', [],...
        'ScanState', 'RS',...
        'Subjects', []),...
    'Spectrum', struct(...
        'Channels', [],...
        'FrequencyRange', 'onesided',...
        'NFFT', 256,...
        'SegmentOverlap', 32,...
        'SpectrumType', 'psd',...
        'Window', hamming(64)));