classdef cohObj < relationObj
    %COHOBJ Generates a standardized coherence data object.
    %   This data object evaluates the magnitude squared coherence between BOLD and EEG data based
    %   on the various user-specified input parameters. This object ultimately calls the "mscohere"
    %   builtin function in MATLAB and uses several parameters (below) that can also be read about
    %   in that function's documentation.
    %
    %   SYNTAX:
    %   cohData = cohObj('PropertyName', PropertyValue...)
    %
    %   OUTPUTS:
    %   cohData:                The coherence data object generated by this function.
    %
    %   INPUTS:
    %   'Channels':             The EEG channels whose time series are to be included in this
    %                           analysis.
    %
    %   'Fs':                   The sampling frequency of the modalities being analyzed (must be the
    %                           same for both EEG and BOLD data).
    %
    %   'MaskMethod':           The method to be used for masking the BOLD data.
    %                           OPTIONS:
    %                               'Correlation'       Uses correlation between an EEG channel and
    %                                                   BOLD data as the mask for BOLD data here. If
    %                                                   chosen, a 'CorrDataFile' property value must
    %                                                   also be specified
    %
    %   'MaskThreshold':        The cutoff threshold for the BOLD data mask.
    %                           EXAMPLES:
    %                               0.875       Top 12.5% of correlation and anticorrelation values
    %                                           for 'Correlation' mask method
    %                               0.9         Top 10% of probability values from MNI gray matter
    %                                           mask
    %   
    %   'TimeShifts':           A numerical or array of numerical values representing the time
    %                           delay(s) in seconds between BOLD and EEG data at which coherence is
    %                           to be evaluated. 
    %                           EXAMPLE:
    %                               4           Specifies that any given BOLD data time point should
    %                                           be compared to an EEG data point occurring 4 seconds
    %                                           earlier in time.
    %
    %   OPTIONAL INPUTS:
    %   'CorrDataFile':         If 'Correlation' is chosen for the masking method, a specific data
    %                           file (MAT file) must also be supplied so that the program knows what
    %                           to load.
    %
    %   'GenerateNull':         A boolean indicating whether or not to generate a null distribution
    %                           for testing the statistical significance of the coherence data. 
    %                           DEFAULT: false
    %
    %   'Mask':                 A specific mask image to be applied to the BOLD data.
    %                           WARNING: This functionality is not yet implemented.
    %
    %   'NumFFT':               The number of FFT points used to calculate power spectral densities
    %                           and cross spectral densities. This parameter determines the
    %                           frequencies at which coherence is estimated.
    %                           DEFAULT: nextpow2(length(window))
    %
    %   'NumOverlap':           The percentage overlap between segments during the FFT step in
    %                           coherence evaluation.
    %                           DEFAULT: 0.5*length(window)
    %
    %   'Scans':                Specific scans to be used in the analysis.
    %                           DEFAULT: 'all'
    %                           EXAMPLES:
    %                               {[1 2] [1] [2]}       Specifies that scans 1 and 2 are included
    %                                                     for subject 1, while only scan 1 is
    %                                                     to be used for subject 2 and scan 2 is to
    %                                                     be used for subject 3.
    %                           
    %
    %   'Subjects':             Specific subjects to be used in the analysis.
    %                           DEFAULT: 'all'
    %                           EXAMPLES:
    %                               [1 2 3 4 5]         Specifies that subjects 1-5 are to be
    %                                                   included.
    %                               [1 3 5 7 8]         Specifies that subjects 1, 3, 5, 7, & 8 are
    %                                                   to be included.
    %   
    %   'Window':               The window function to be used in coherence evaluation.
    %                           DEFAULT: hamming((1/8)*length(data))
    %
    %
    %   Written by Josh Grooms on 20130913
    
    
    %% Constructor Method
    methods
        function cohData = cohObj(cohStruct)
            %COHOBJ Constructs the coherence data object using the various input parameters.
            if nargin ~= 0
                cohData = initialize(cohData, cohStruct);
                cohData = coherence(cohData);
            end                
        end
    end
        
        
    %% Public Methods
    methods        
        % Average data together
        meanCohData = mean(cohData)
        % Display the data
        plot(cohData, varargin)
        % Store the data
        store(cohData, varargin)
        % Threshold the data for significance
        meanCohData = threshold(meanCohData, meanNullData)
    end
    
    
    %% Protected Methods
    methods %(Access = protected)
        % Evaluate coherence between the data
        cohData = coherence(cohData)
        % Initialize the data object
        cohData = initialize(cohData, cohStruct)
    end
end
        
    