function cohStruct = parameters(~)
%PARAMETERS Returns a parameter structure with default values for coherence analysis.
%
%   SYNTAX:
%
%   OUTPUT:
%
%   INPUT:
%
%   Written by Josh Grooms on 20130910
%       20131001:   Added a section for thresholding coherence values


%% The Coherence Data Object Input Parameter Structure
load masterStructs

cohStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{'fb', 'fb'}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-EEG',...
        'ParentData', [],...
        'Relation', 'MS Coherence',...
        'Scans', [],...
        'ScanState', 'RS',...
        'Subjects', []),...
    'Coherence', struct(...
        'Channels', [],...
        'Control', 'BOLD Nuisance',...
        'GenerateNull', false,...
        'Masking', struct(...
            'Method', 'Correlation',...
            'File', [],...
            'Image', [],...
            'Shift', 4,...
            'Threshold', 0.9),...
        'NFFT', [],...
        'SegmentOverlap', [],...
        'Window', []),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Parallel', 'gpu',...
        'Tails', 'upper'));