classdef BrainPlot < Window
%BRAINPLOT Displays data in an EEG- or fMRI-style plot or montage of plots.
%   This object displays EEG or MRI data in a montage. It accepts 3-4D MRI images and 2-3D EEG data arrays, as described
%   below. For MRI data, data are displayed as color-coded images. EEG data is displayed as a color-coded scaled spatial
%   layout of EEG electrodes.
%
%   SYNTAX:
%   brainData = brainPlot(plotType, plotData, 'PropertyName', PropertyValue...)
%
%   OPTIONAL OUTPUT:
%   brainData:              BRAINPLOT
%                           A handle to the outputted data object containing all necessary information to create an
%                           image montage. This output is optional.
%
%   INPUTS:
%   plotType:               STRING
%                           The type of plot to be generated by the function (either EEG electrode spatial maps or MRI
%                           colored images. This variable is case insensitive.
%                           OPTIONS:
%                               'EEG'
%                               'MRI'
%
%   plotData:               2D, 3D, or 4D ARRAY
%                           The data to be plotted. Data must be the specified format to work with this object. MRI data
%                           can be 2, 3, or 4 dimensional. EEG data can be either 1, 2, or 3 dimensional. Threshold data
%                           by setting insignificant values to NaN.
%
%                           OPTIONS:
%                               MRI Data:
%                               [X, Y]          - A single 2D MRI image.
%                               [X, Y, Z]       - A single 3D MRI image. Slices will be plotted vertically unless 
%                                                 specified using 'XDim' and 'YDim' properties.
%                               [X, Y, Z, Var1] - 3D MRI images across some variable (e.g. time). Slices will be plotted 
%                                                 vertically and the 4th dimension will be plotted horizontally, unless
%                                                 otherwise specified.
%
%                               EEG Data:
%                               [C]             - A vector of data (one point per channel).
%                               [C, Var1]       - An array of data where each row corresponds to a single channel's data 
%                                                 across some other variable (e.g. time or time shift). The second
%                                                 dimension will be plotted horizontally unless otherwise specified
%                                                 using 'XDim' and 'YDim'.
%                               [C, Var1, Var2] - EEG data across two variables. Each column of the array will be 
%                                                 plotted horizontally and each page will be plotted veritcally, unless
%                                                 otherwise specified.
%
%   OPTIONAL INPUTS:
%   'Anatomical':           3D ARRAY
%                           An anatomical (T1) 3D image. Input these data in the same spatial format as the "plotData"
%                           parameter, with the same number of slices. The anatomical image will be displayed on
%                           thresholded data in place of values that do not pass significance testing.
%                           DEFAULT: []
%
%   'AxesColor':            STRING or [DOUBLE, DOUBLE, DOUBLE]
%                           The color of the bounding axes box and all associated text. Acceptable inputs include
%                           standard MATLAB string color specifiers or a vector of RGB values.
%                           DEFAULT: 'w' OR [1 1 1]
%
%   'Channels':             {STRINGS}
%                           A cell array of EEG channel labels in the same ordering as the first dimension of the input
%                           data array. If calling for an MRI plot, this variable is not used.
%                           DEFAULT: all 68 EEG channels in standard ordering (found in eegChannels.mat)
%   
%   'CLim':                 [DOUBLE, DOUBLE]
%                           A two-element vector specifying the [MIN MAX] in data units to be 
%                           mapped to color extremes. By default, this parameter is calculated 
%                           automatically using absolute data extremes. 
%                           DEFAULT: []
%
%   'Color':                STRING or [DOUBLE DOUBLE DOUBLE]
%                           The background color of the figure and all axes. Acceptable inputs include standard MATLAB
%                           string color specifiers or a vector of RGB values.
%                           DEFAULT: 'k' OR [0 0 0]
%
%   'Colorbar':             BOOLEAN
%                           A Boolean controlling whether or not a colorbar is present on the figure.
%                           DEFAULT: true
%                           OPTIONS: true OR false OR 'on' OR 'off'
%
%   'ColorbarLabel':        STRING
%                           The vertical text label for the colorbar.
%                           DEFAULT: []
%
%   'Colormap':             COLORMAP
%                           The colormap being utilized by the figure.
%                           DEFAULT: jet(256)
%
%   'Position':             STRING or [INTEGER, INTEGER]
%                           A string (or actual numerical position in pixels, if you want) indicating the position of
%                           the window on-screen. This parameter is highly flexible, and ordering does not matter. Any
%                           combination of strings from the options below (one specifying a vertical and another
%                           specifying a horizontal position, separated by a hyphen) will work. This has no effect when
%                           the window size is set to "fullscreen".
%                           DEFAULT: 'top-right' 
%                           OPTIONS: 
%                               Numerical:
%                               [X, Y] - Specifying the X and Y position (in pixels) of the lower left window corner.
%                               
%                               Strings:
%                               'left'   OR 'west'
%                               'right'  OR 'east'
%                               'top'    OR 'upper' OR 'north'
%                               'middle' OR 'center'
%                               'bottom' OR 'lower' OR 'south'
%
%   'Size':                 STRING or [INTEGER, INTEGER]
%                           A string (or actual numerical size in pixels, if you want) indicating the size of the window
%                           on-screen. This parameter is flexible, and several options will work. 
%                           DEFAULT: 'fullscreen'
%                           OPTIONS:
%                               Numerical:
%                               [X, Y] - Specifying the width and height (in pixels) of the entire figure window
%                                        (including borders). The figure window will automatically reposition itself to
%                                        fit on-screen if this input extends the window beyond.
%
%                               Strings:
%                               'default'               - The MATLAB default window size.
%                               'halfscreen' OR 'half'  - Window will fill half of the
%                                                         horizontal screen space.
%                               'fullscreen' OR 'full'  - Window will fill the whole screen.
%
%   'Threshold':            [DOUBLE, DOUBLE]
%   
%   'Title':                STRING
%                           The plot title string.
%                           DEFAULT: []
%
%   'Visible':              BOOLEAN
%                           A boolean indicating whether or not the figure is visible to the user (same as built-in
%                           figure visibility property).
%                           DEFAULT: true
%
%   'XDim':                 INTEGER
%                           The scalar dimension of the data to be plotted along the x-axis of the montage.
%                           DEFAULT: 2 (for EEG data) OR 4 (for MRI data)
%
%   'XLabel':               STRING
%                           The x-axis label string (same as the built-in axes property). Just input the string here
%                           (using "set" or dot-notation) and it will automatically be added to the plot and colored.
%                           DEFAULT: []
%
%   'XTickLabel':           {STRINGS} or [DOUBLES]
%                           The x-axis tick labels (same as the built-in axes property). Just add the array or cell
%                           array of labels to this property (using "set" or dot-notation) and it will be automatically
%                           added to the plot and colored.
%                           DEFAULT: []
%
%   'YDim':                 INTEGER
%                           The scalar dimension of the data to be plotted along the y-axis of the montage.
%                           DEFAULT: 3 (for both EEG and MRI data)
%
%   'YLabel':               STRING
%                           The y-axis label string (same as the built-in axes property). Just add the array or cell
%                           array of labels to this property (using "set" or dot-notation) and it will be automatically
%                           added to the plot and colored.
%                           DEFAULT: []
%
%   'YTickLabel':           {STRINGS} or [DOUBLES]
%                           The y-axis tick labels (same as the built-in axes property). Just add the array or cell
%                           array of labels to this property (using "set" or dot-notation) and it will be
%                           automatically added to the plot and colored.
%                           DEFAULT: []

%% DEPENDENCIES
%
%   @Window
%   
%   assignInputs
%   istrue
%   scale2rgb
%   str2rgb
%   where

%% CHANGELOG
%   Written by Josh Grooms on 20130626
%       20130702:   Implemented MRI plotting capabilities. Also implemented anatomical underlay for thresholded images.
%       20130711:   Implemented a function for save figure images. Added documentation for "CLim" property.
%       20130717:   Set the default window position to screen center.
%       20130809:   Re-wrote the method TOGGLELISTENERS here (removed from WINDOWOBJ). Updated to work with re-written
%                   WINDOWOBJ.
%       20140625:   Removed dependencies on my personal file structure. Updated documentation. Changed some default 
%                   settings of the Store function and implemented file overwrite protection. 
%       20140828:   Major reorganization and update to this class (essentially a re-write). Updated for compatibility
%                   with major updates to the WINDOW class (formerly WINDOWOBJ). Moved the code for several methods here
%                   to the class definition file and eliminated some superfluous methods altogether. Compeletely
%                   reorganized the class properties and changed the way users/programs interface with them. Implemented
%                   several new features, in particular some relating to plot labeling (e.g. tick labels, titles, etc.).

%% TODOS
%   - Merge PLOTEEG static method & the separate EEGMAP function.
%   - Make axis tick labels that can be rotated & more finely controlled.
%   - Implement variable numbers of axis tick labels



    %% Brain Plot Properties
    
    properties (Dependent)
        AxesColor               % The color of the primary plot axes.
        CLim                    % The [MIN, MAX] data values that are mapped to colormap extremes.
        ColorbarLabel           % A label string for the plot's colorbar.
        Title                   % The title string of the plot.
        XLabel                  % The x-axis label string.
        XTickLabel              % The individual x-axis tick labels.
        YLabel                  % The y-axis label string.
        YTickLabel              % The individual y-axis tick labels.
    end

    properties (AbortSet)
        Anatomical              % A 3D array containing an anatomical brain image (only applies to MRI-type plots).
        Channels                % A cell array of strings containing EEG channel labels (only applies to EEG-type plots).
        MajorFontSize
        MinorFontSize
        XDim                    % The data dimension to be plotted along the x-axis.
        YDim                    % The data dimension to be plotted along the y-axis.
    end
    
    properties (Access = private, Hidden)
        ElementAspect           % The normalized [WIDTH, HEIGHT] of each montage element.
        ElementSize             % The [WIDTH, HEIGHT] of each montage element in pixels.
        MontageSize             % The [NUMROWS, NUMCOLS] of the whole montage.
        PlotType                % The BrainPlotType enumerator specifying the type of data being displayed.
        XTick                   % 
        YTick
    end
    
    
    
    %% Constructor Method
    methods
        function H = BrainPlot(plotData, varargin)
            %BRAINPLOT - Constructs a window object & initializes the plotting environment.
            
            % Initialize a window object for displaying the data
            H = H@Window(...
                'Color', 'k',...
                'Colormap', jet(256),...
                'MenuBar', 'off',...
                'NumberTitle', 'off',...
                'Position', WindowPositions.CenterCenter,...
                'Size', WindowSizes.FullScreen); drawnow
            
            if nargin ~= 0
                
                % Ensure only numeric arrays were inputted
                if ~isnumeric(plotData); error('Only numeric data arrays may be displayed using BrainPlot'); end
                
                % Override defaults with any user inputs
                climBound = max(abs(plotData(:)));
                inStruct = struct(...
                    'Anatomical', [],...
                    'AxesColor', 'w',...
                    'CLim', [-climBound, climBound],...
                    'Color', 'k',...
                    'ColorbarLabel', [],...
                    'Colormap', jet(256),...
                    'MajorFontSize', 25,...
                    'MinorFontSize', 20,...
                    'Title', [],...
                    'XLabel', [],...
                    'XTickLabel', [],...
                    'YLabel', [],...
                    'YTickLabel', []);
                assignInputs(inStruct, varargin, 'structOnly');
                
                % Determine the type of data based on its dimensionality
                if (size(plotData, 1) == 68); H.PlotType = BrainPlotTypes.EEG;
                else H.PlotType = BrainPlotTypes.MRI;
                end
                
                % Fill in object properties
                H.Data = plotData;
                H.InitializePrimaryAxes;
                H.Colorbar = colorbar('EastOutside');
                H.DetermineMontageDimensionality;
                H.CalculateElementSize;
                H.FitPrimaryAxesToMontage;
                H.InitializeMontageAxes;
                
                % Transfer user inputs to object properties
                propNames = fieldnames(inStruct);
                for a = 1:length(propNames)
                    if ~isempty(inStruct.(propNames{a})); 
                        set(H, propNames{a}, inStruct.(propNames{a}));
                    end
                end
                
                % Plot the data
                H.Plot;
                
            end
        end
    end
    
    
    
    %% Public Methods
    methods
        
        % Store the image
        Store(brainData, varargin)
        
    end
    
    
    
    %% Get & Set Methods
    methods
        
        % Get methods
        function color  = get.AxesColor(H)
            color = get(H.Axes.Primary, 'XColor');
        end
        function clim   = get.CLim(H)
            clim = get(H.Axes.Primary, 'CLim');
        end
        function clabel = get.ColorbarLabel(H)
            clabel = get(get(H.Colorbar, 'YLabel'), 'String');
        end
        function title  = get.Title(H)
            title = get(get(H.Axes.Primary, 'Title'), 'String');
        end
        function xlabel = get.XLabel(H)
            xlabel = get(get(H.Axes.Primary, 'XLabel'), 'String');
        end
        function ylabel = get.YLabel(H)
            ylabel = get(get(H.Axes.Primary, 'YLabel'), 'String');
        end
        
        % Set methods
        function set.AxesColor(H, color)
            set(H.Axes.Primary, 'XColor', color, 'YColor', color);
            set(get(H.Axes.Primary, 'Title'), 'Color', color);
            set(get(H.Axes.Primary, 'XLabel'), 'Color', color);
            set(get(H.Axes.Primary, 'YLabel'), 'Color', color);
            set(get(H.Colorbar, 'YLabel'), 'Color', color);
        end
        function set.CLim(H, clim)
            set(H.Axes.Primary, 'CLim', clim);
        end
        function set.ColorbarLabel(H, clabel)
            set(get(H.Colorbar, 'YLabel'), 'String', clabel);
        end
        function set.MajorFontSize(H, fsize)
            set(get(H.Colorbar, 'YLabel'), 'FontSize', fsize);
            set(get(H.Axes.Primary, 'Title'), 'FontSize', fsize);
            set(get(H.Axes.Primary, 'XLabel'), 'FontSize', fsize);
            set(get(H.Axes.Primary, 'YLabel'), 'FontSize', fsize);
        end
        function set.MinorFontSize(H, fsize)
            set(H.Colorbar, 'FontSize', fsize);
            set(H.Axes.Primary, 'FontSize', fsize);
        end
        function set.Title(H, title)
            set(get(H.Axes.Primary, 'Title'), 'String', title);
        end
        function set.XLabel(H, xlabel)
            set(get(H.Axes.Primary, 'XLabel'), 'String', xlabel);
        end
        function set.XTickLabel(H, tlabels)
            spacing = 1/H.MontageSize(2);
            halfSpacing = 0.5*spacing;
            ticks = linspace(halfSpacing, 1 - halfSpacing, H.MontageSize(2));
            set(H.Axes.Primary, 'XTick', ticks, 'XTickLabel', tlabels);
        end
        function set.YLabel(H, ylabel)
            set(get(H.Axes.Primary, 'YLabel'), 'String', ylabel);
        end
        function set.YTickLabel(H, tlabels)
            spacing = 1/H.MontageSize(1);
            halfSpacing = 0.5*spacing;
            ticks = linspace(halfSpacing, 1 - halfSpacing, H.MontageSize(1));
            set(H.Axes.Primary, 'YTick', ticks, 'YTickLabel', tlabels);
        end
        
    end
    
    
    
    %% Static Methods
    methods (Static)
        
        PlotEEG(A, data, showLabels);
        % Generate fused functional & anatomical images
        fusedImage = FuseImages(boldImage, anatomicalImage, clim)        
        
    end
    
    
    
    %% Private Methods
    methods (Access = private)
        
        % Calculate montage element sizes
        function CalculateElementSize(H)
            %CALCULATEELEMENTSIZE - Calculates the size of montage elements and a new primary axes position/size vector.
            posAxes = get(H.Axes.Primary, 'Position');
            asize = posAxes(3:4);
            width = asize(1)/H.MontageSize(2);
            height = width * (H.ElementAspect(2) / H.ElementAspect(1));
            if (height * H.MontageSize(1) > asize(2))
                height = asize(2) / H.MontageSize(1);
                width = height * (H.ElementAspect(1) / H.ElementAspect(2));
            end
            H.ElementSize = [width, height];
        end
        % Determine number & aspect ratio of montage elements
        function DetermineMontageDimensionality(H)
            %DETERMINEMONTAGEDIMENSIONALITY - Calculates the montage size and element aspect ratio based on the data.
            switch (H.PlotType) 
                case BrainPlotTypes.EEG
                    H.MontageSize = [size(H.Data, 3), size(H.Data, 2)];         % [numRows, numCols]
                    H.ElementAspect = [1, 1];                                   % [width, height], square plots
                case BrainPlotTypes.MRI
                    H.MontageSize = [size(H.Data, 3), size(H.Data, 4)];         % [numRows, numCols]
                    H.ElementAspect = [size(H.Data, 1), size(H.Data, 2)];       % Reversed (MRI data are permuted later)
                    H.ElementAspect = H.ElementAspect./max(H.ElementAspect);    % [width, height], scaled to max value
            end
        end
        % Fit the primary axes to the montage
        function FitPrimaryAxesToMontage(H)
            
            posFig = getpixelposition(H.FigureHandle);
            apos = [0, 0, H.ElementSize .* [H.MontageSize(2) H.MontageSize(1)]];
            apos(1) = (posFig(1) + posFig(3) - apos(3)) / 2;
            apos(2) = (posFig(2) + posFig(4) - apos(4)) / 2;
            set(H.Axes.Primary, 'Position', apos);
        end
        % Create axes that contain & label the image montage
        function InitializePrimaryAxes(H)
            %INTIALIZEPRIMARYAXES - Sets up the visible axes that surround and label the montage.
            H.Axes.Primary = axes(...
                'Units', 'pixels',...
                'Box', 'on',...
                'Color', 'none',...
                'LineWidth', 5,...
                'Parent', H.FigureHandle,...
                'TickLength', [0 0],...
                'XLim', [0 1],...
                'XTick', [],...
                'YLim', [0 1],...
                'YTick', []);
        end
        % Create an array of axes to serve as the montage elements
        function InitializeMontageAxes(H)
            %INITIALIZEMONTAGEAXES - Initializes an array of axes that form the individual image montage elements.
            H.Axes.Montage = zeros(H.MontageSize);
            apos = get(H.Axes.Primary, 'Position');
            epos = [0, 0, H.ElementSize];
            for a = 1:H.MontageSize(1)
                for b = 1:H.MontageSize(2)
                    epos(1) = (b - 1) * H.ElementSize(1) + apos(1) - 1;
                    epos(2) = (a - 1) * H.ElementSize(2) + apos(2) + 1;
                    H.Axes.Montage(a, b) = H.NewElement(epos);
                end
            end
            H.Axes.Montage = flipdim(H.Axes.Montage, 1);    % Flipped so ordering starts from the upper left corner
        end
        % Create individual montage element axes
        function A = NewElement(H, position)
            %NEWELEMENT - Create a new montage element at the specified position and return a handle to it.
            A = axes(...
                'Units', 'pixels',...
                'Box', 'off',...
                'CLim', H.CLim,...
                'CLimMode', 'manual',...
                'Color', 'none',...
                'Parent', H.FigureHandle,...
                'Position', position,...
                'XLim', [0, 1],...
                'XTick', [],...
                'YLim', [0, 1],...
                'YTick', []);
        end
        % Plot the inputted data in the image montage
        function Plot(H)
            %PLOT - Separates and displays the brain data within each montage element based on the type of data present.
            
            switch (H.PlotType)
                
                case BrainPlotTypes.EEG
                    for a = 1:H.MontageSize(1)
                        for b = 1:H.MontageSize(2)
                            BrainPlot.PlotEEG(H.Axes.Montage(a, b), H.Data(:, b, a), false);
                        end
                    end
                    
                case BrainPlotTypes.MRI
                    data = permute(H.Data, [2 1 3 4]);
                    data = flipdim(data, 3);
                    if (~isempty(H.Anatomical)); anatomical = permute(double(H.Anatomical), [2 1 3]);
                    else anatomical = [];
                    end
                    
                    for a = 1:H.MontageSize(1)
                        for b = 1:H.MontageSize(2)
                            currentData = data(:, :, a, b);
                            if isempty(anatomical)
                                currentData = scale2rgb(currentData, 'CLim', H.CLim);
                            else
                                currentData = H.FuseImages(currentData, anatomical(:, :, a), H.CLim);
                            end
                            image(...
                                'CData', currentData,...
                                'Parent', H.Axes.Montage(a, b),...
                                'XData', [0, 1],...
                                'YData', [0, 1]);
                            drawnow;
                        end
                    end       
                    
            end
        end
        
    end
    
    
    
end