%% 20140721 


%% Preprocessing Parameter Structure
paramStruct = struct(...
    'General', struct(...
        'ConvertToStructure', false,...
        'LargeData', false,...
        'OutputPath', 'C:/Users/jgrooms/Desktop/Data Sets/Raw Data/Schumacher Data',...
        'Scans', {{[1]}},...
        'ScanState', 'RS',...
        'Subjects', 1,...
        'UseSliceTimingCorrection', false),...
    'Initialization', struct(...
        'AnatomicalFolderStr', 't1_MPRAGE_',...
        'DataPath', 'C:/Users/jgrooms/Desktop/Data Sets/Raw Data/Schumacher Data',...
        'FunctionalFolderStr', 'fMRI_\d_\d\d',...
        'IMGFolderStr', 'IMG',...
        'MNIBrain', 'C:/Users/jgrooms/Dropbox/Globals/MNI/template/T1.nii',...
        'MNIFolder', 'C:/Users/jgrooms/Dropbox/Globals/MNI',...
        'ROIFolder', 'C:/Users/jgrooms/Dropbox/Globals/MNI/roi',...
        'SegmentsFolder', 'C:/Users/jgrooms/Dropbox/Globals/MNI/segments',...
        'SubjectFolderStr', 'DMC_003'),...
    'Segmentation', struct(...
        'BiasReg', 0.0001,...
        'BiasFWHM', 60,...
        'Cleanup', false,...
        'MaskImage', {{''}},...
        'NumGauss', [2 2 2 4],...
        'OutputCorrected', true,...
        'OutputCSF', [0 0 1],...
        'OutputGM', [0 0 1],...
        'OutputWM', [0 0 1],...
        'RegType', 'mni',...
        'SampleDistance', 3,...
        'WarpReg', true,...
        'WarpCutoff', 25),...
    'Registration', struct(...
        'CostFunction', 'nmi',...
        'FWHMSmoothing', [7 7],...
        'Interpolation', 1,...
        'Masking', 0,...
        'OutputPrefix', 'r',...
        'Separation', [4 2],...
        'Tolerances', [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001 0.001],...
        'Wrapping', [0 0 0]),...
    'Normalization', struct(...
        'AmtRegularization', 1,...
        'BoundingBox', [-78 -112 -50; 78 76 85],...
        'DCTCutoff', 25,...
        'Interpolation', 1,...
        'Masking', false,...
        'NormPrefix', 'w',...
        'NumIterations', 16,...
        'Preservation', 0,...
        'RegPrefix', 'r',...
        'Regularization', 'mni',...
        'SourceSmoothing', 8,...
        'TemplateImage', [],...
        'TemplateSmoothing', 0,...
        'TemplateWeightImage', {''},...
        'VoxelSize', [2 2 2],...
        'Wrapping', [0 0 0]),...
    'Conditioning', struct(...
        'BlurMasks', true,...
        'CSFCutoff', 0.2,...
        'DetrendOrder', 2,...
        'FilterData', true,...
        'FilterLength', 45,...
        'GMCutoff', 0.1,...
        'MeanCutoff', 0.2,...
        'NumPCToRegress', NaN,...
        'NumTRToRemove', 0,...
        'Passband', [0.01 0.08],...
        'PCAVarCutoff', 0.0001,...
        'RegressCSF', false,...
        'RegressGlobal', false,...
        'SpatialBlurSigma', 2,...
        'SpatialBlurSize', 3,...
        'UsePCA', false,...
        'UseZeroPhaseFilter', true,...
        'WMCutoff', 0.15));


%% 1436 - Attempting to Resolve BOLD Preprocessing Issues with Schumacher Data

boldObj(paramStruct);
