function powerSpectra(eegData, varargin)
%POWERSPECTRA Power spectrum analysis on EEG data objects.
%
%   Written by Josh Grooms on 20130202


%% Initialize
% Initialize the defaults structure
inStruct = struct(...
    'averageData', true,...
    'electrodes', [],...
    'lengthSegment', 60000,...
    'pctOverlap', 99.5,...
    'rangeFreqs', 0:0.001:0.1,...
    'scans', [],...
    'subjects', [],...
    'visibleFigs', 'off');
assignInputs(inStruct, varargin);

%% Generate & Save the Spectral Data
spectralData = spectralObj(...
    'eegData', eegData,...
    'electrodes', electrodes,...
    'lengthSegment', lengthSegment,...
    'pctOverlap', pctOverlap,...
    'rangeFreqs', rangeFreqs,...
    'subjects', subjects,...
    'scans', scans);
store(spectralData);

%% Create Averages of the Spectral Data
if averageData
    meanSpectralData = average(spectralData);
end

%% Image the Spectral Data
% Image the individual spectra
plot(spectralData)

% Image the average spectra
plot(meanSpectralData)
