function paramStruct = Parameters(~)
%PARAMETERS Returns a parameter structure with default values for BOLD data preprocessing.
%   This function exists only to return a default parameter structure that governs the entire BOLD data object usage.
%   The fields and substructures within the output constitute all possible user input accepted during the instantiation
%   of a BOLD object.
%
%   SYNTAX:
%   paramStruct = Parameters(boldObj)
%
%   OUTPUT:
%   paramStruct:    STRUCT
%                   This is a structure whose fields and substructure fields constitute the only available user input to 
%                   the BOLD data object. Default values are filled in. Change any of these values as needed and input
%                   the structure back into BOLDOBJ or any compatible analysis methods using the STRUCT2VAR function. 
%                   
%                   EXAMPLE:
%                       paramStruct = parameters(boldObj);
%                       % Change field values as needed
%                       .
%                       .
%                       .
%                       boldData = boldObj(paramStruct);
%
%   INPUTS:
%   boldObj:        The input to this function must always be "boldObj" (without quotes) and nothing else. This is so 
%                   MATLAB knows which method to call to return the correct parameter structure. "boldObj" is the class
%                   name of the BOLD data object.



%% CHANGELOG
%   Written by Josh Grooms on 20130707
%       20130711:   Updated to include a "General" section with frequenctly updated parameters.
%       20130730:   Implemented ability to convert object into old human_data structures before saving.
%       20140612:   Removed the switch/case originally intended for multiple parameter structures. These were never
%                   implemented and I doubt they ever will be. Updated the documentation accordingly.
%       20140707:   Added in the option to use zero-phase FIR filtering during signal conditioning to prevent having to
%                   crop out sections of time series.
%       20140720:   Added in the option to turn off slice-timing corrections. This shouldn't be used on data sets with
%                   fast TRs.

%% TODOS
% Immediate
%   - Parameter verification before preprocessing starts



%% Select & Return the Parameter Structure for Data Preprocessing
paramStruct = struct(...
    'General', struct(...
        'ConvertToStructure', false,...
        'LargeData', false,...
        'OutputPath', 'E:\Graduate Studies\Lab Work\Data Sets\Raw Data\SchumacherData',...
        'Scans', {{[1]}},...
        'ScanState', 'RS',...
        'Subjects', 1,...
        'UseSliceTimingCorrection', false),...
    'Initialization', struct(...
        'AnatomicalFolderStr', 't1_MPRAGE_',...
        'DataPath', 'E:\Graduate Studies\Lab Work\Data Sets\Raw Data\SchumacherData',...
        'FunctionalFolderStr', 'fMRI_\d_\d\d',...
        'IMGFolderStr', 'IMG',...
        'MNIBrain', 'C:\Users\Josh\Dropbox\Globals\MNI\template\T1.nii',...
        'MNIFolder', 'C:\Users\Josh\Dropbox\Globals\MNI',...
        'ROIFolder', 'C:\Users\Josh\Dropbox\Globals\MNI\roi',...
        'SegmentsFolder', 'C:\Users\Josh\Dropbox\Globals\MNI\segments',...
        'SubjectFolderStr', 'DMC_003'),...
    'Segmentation', struct(...
        'BiasReg', 0.0001,...
        'BiasFWHM', 60,...
        'Cleanup', false,...
        'MaskImage', {{''}},...
        'NumGauss', [2 2 2 4],...
        'OutputCorrected', true,...
        'OutputCSF', [0 0 1],...
        'OutputGM', [0 0 1],...
        'OutputWM', [0 0 1],...
        'RegType', 'mni',...
        'SampleDistance', 3,...
        'WarpReg', true,...
        'WarpCutoff', 25),...
    'Registration', struct(...
        'CostFunction', 'nmi',...
        'FWHMSmoothing', [7 7],...
        'Interpolation', 1,...
        'Masking', 0,...
        'OutputPrefix', 'r',...
        'Separation', [4 2],...
        'Tolerances', [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001 0.001],...
        'Wrapping', [0 0 0]),...
    'Normalization', struct(...
        'AmtRegularization', 1,...
        'BoundingBox', [-78 -112 -50; 78 76 85],...
        'DCTCutoff', 25,...
        'Interpolation', 1,...
        'Masking', false,...
        'NormPrefix', 'w',...
        'NumIterations', 16,...
        'Preservation', 0,...
        'RegPrefix', 'r',...
        'Regularization', 'mni',...
        'SourceSmoothing', 8,...
        'TemplateImage', [],...
        'TemplateSmoothing', 0,...
        'TemplateWeightImage', {''},...
        'VoxelSize', [2 2 2],...
        'Wrapping', [0 0 0]),...
    'Conditioning', struct(...
        'BlurMasks', true,...
        'CSFCutoff', 0.2,...
        'DetrendOrder', 2,...
        'FilterData', true,...
        'FilterLength', 45,...
        'GMCutoff', 0.1,...
        'MeanCutoff', 0.2,...
        'NumPCToRegress', NaN,...
        'NumTRToRemove', 0,...
        'Passband', [0.01 0.08],...
        'PCAVarCutoff', 0.0001,...
        'RegressCSF', false,...
        'RegressGlobal', false,...
        'SpatialBlurSigma', 2,...
        'SpatialBlurSize', 3,...
        'UsePCA', false,...
        'UseZeroPhaseFilter', true,...
        'WMCutoff', 0.15));

% Add in defaults that couldn't be filled in just before
paramStruct.Normalization.TemplateImage = {[paramStruct.Initialization.MNIBrain ',1']};