function boldStruct = ToStruct(boldObject)
%TOSTRUCT Converts BOLD data objects into data structures.
%   This function is used to convert BOLD objects into data structures. Structures are a value-type in MATLAB and as
%   such are often easier and more intuitive to deal with in this language. Additionally, they offer a lot more
%   flexibility in terms of dynamic field creation and removal.
%
%   However, there are downsides to this conversion. While structures appear not to suffer from the code bload that
%   classes can have, most of the quality control benefits inherent to classes are lost. Examples include: type-safe
%   methods, subclassing, resticted access to fields/methods, and validation of field modifications. Also, as a
%   reference-type, the correct use of classes can eliminate some significant computational overhead that is incurred
%   when using a structure (this is especially apparent for large data sets).
%
%   This method exists so that the user may freely work with a BOLD data set without any restrictions or the need to
%   work with the specialized class methods. 
%
%   SYNTAX:
%   boldStruct = ToStruct(boldObject)
%
%   OUTPUT:
%   boldStruct:     STRUCT
%                   A value-type BOLD data structure in exactly the same apparent format as the inputted data object.
%                   This structure may be editted freely but can no longer be used with any of the methods that are
%                   associated with the boldObj class.
%
%   INPUT:
%   boldObject:     BOLDOBJ
%                   A reference-type BOLD data object that is typically generated by preprocessing raw DICOM images. 



%% CHANGELOG
% Written by Josh Grooms on 20130730
%       20140612:   Completely overhaul of this function. Changed the function same and class signature to match new
%                   standards and to reflect a change in functionality. This method no longer converts objects into
%                   Garth's old "human_data" structures (which haven't been used in a very long time), but instead
%                   converts them into structures that are essentially mirror images of the object itself. 



%% Convert BOLD Objects into human_data Structures
% Initialize the BOLD data structure
boldStruct(numel(boldObject)) = struct();

% Transfer object properties into structure fields
propNames = properties(boldObject(1));
for a = 1:numel(boldObject)
    for b = 1:length(propNames)
        boldStruct(a).(propNames{b}) = boldObject(a).(propNames{b});
    end
end

% Reshape the data structure into the same dimensionality & ordering as the object
boldStruct = reshape(boldStruct, size(boldObject));