function a_xcorr_global_global
%% Initialize
load masterStructs.mat

% Change parameter structure values
paramStruct.xcorr.Global_Global = struct(...
    'subjects', [paramStruct.general.subjects],...
    'scans', {paramStruct.general.scans},...
    'shiftsTime', [-20:2:20],...
    'imageShifts', [-20:2:20],...
    'alphaVal', 0.05,...
    'imageSingleSubjects', true,...
    'visibleFigs', 'off',...
    'comments', 'For publication: (DC-Global)-Global Cross-Correlation');

% Change file structure values
fileStruct.analysis.xcorr.Global_Global = struct(...
    'boldDataPath', [fileStruct.paths.MAT_files '\BOLD'],...
    'eegDataFile', [fileStruct.paths.MAT_files '\EEG\eegData_dcGR_20130120.mat'],...
    'savePathData', [fileStruct.paths.MAT_files '\xcorr'],...
    'savePathImage', [fileStruct.paths.analyses '\Cross-Correlation\Global-Global\'],...
    'saveID', '20130308');
save(fileStruct.files.masterStructs, 'fileStruct', 'paramStruct')


%% Run the Analysis
% Cross-correlate the global signals
% arx_realGG(fileStruct, paramStruct)

% Average the data together to reduce size
% ara_corrGG(fileStruct, paramStruct)

% Image the data
ai_corrGG(fileStruct, paramStruct)