function a_xcorr_EEG_Global

%% Initialize
load masterStructs.mat;

% Change parameter structure values
paramStruct.xcorr.EEG_Global = struct(...
    'subjects', [paramStruct.general.subjects],...
    'scans', {paramStruct.general.scans},...
    'shiftsTime', [-50:2:50],...
    'imageShifts', [-16:2:16],...
    'alphaVal', 0.05,...
    'imageSingleSubjects', true,...
    'visibleFigs', 'off',...
    'parallelSwitch', true,...
    'comments', 'For publication: (DC-EEG)-(BOLD Global Signal) Cross-Correlation (Thresholding at alpha = 0.05)');

% Change file structure values
fileStruct.analysis.xcorr.EEG_Global = struct(...
    'eegDataFile', [fileStruct.paths.MAT_files '\EEG\eegData_dc.mat'],...
    'boldDataPath', [fileStruct.paths.MAT_files '\BOLD'],...
    'savePathData', [fileStruct.paths.MAT_files '\xcorr'],...
    'savePathImage', [fileStruct.paths.analyses '\Cross-Correlation\EEG-Global\Five Pct Alpha'],...
    'saveID', '20130130',...
    'saveTag', 'dc');
save(fileStruct.files.masterStructs, 'fileStruct', 'paramStruct')


%% Run the Analysis
% Cross-correlate the real data
% arx_realEG(fileStruct, paramStruct)

% Generate a null distribution for bootstrapping
% arx_nullEG(fileStruct, paramStruct)

% Average the data together to reduce size
% ara_corrEG(fileStruct, paramStruct)

% Bootstrap the data for significance
% arb_corrEG(fileStruct, paramStruct)

% Image the data
ai_corrEG(fileStruct, paramStruct)




