function ccStruct = parameters(~)
%PARAMETERS Returns a parameter structure with default values for correlation analysis.
%   This function exists only to return a default parameter structure that governs the entire correlation analysis. The
%   fields and substructures within the output constitute all possible user input accepted during the instantiation of a
%   correlation object.
%
%   SYNTAX:
%   paramStruct = parameters(corrObj)
%
%   OUTPUT:
%   ccStruct:       This is a structure whose fields and substructure fields constitute the only available user input to
%                   the correlation data object. Default values are filled in. Change any of these values as needed and
%                   input the structure back into CORROBJ using the STRUCT2VAR function.
%                   EXAMPLE:
%                       paramStruct = parameters(corrObj);
%                       % Change field values as needed
%                       .
%                       .
%                       .
%                       paramCell = struct2var(paramStruct);
%                       corrData = corrObj(paramCell{:});
%
%   INPUT:
%   corrObj:        The input to this function must always be "corrObj" (without quotes) and nothing else. This is so 
%                   MATLAB knows which method to call to return the correct parameter structure. "corrObj" is the class
%                   name of the correlation data object.
%
%   Written by Josh Grooms on 20130702
%       20130707:   Updated documentation errors 
%       20130717:   Updated to include a masking parameter during thresholding to cut down on computation time.


%% The Correlation Data Object Input Parameter Structure
load masterStructs
gmMask = load_nii(fileStruct.Files.Segments.Gray); gmMask = gmMask.img;

ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-EEG',...
        'Relation', 'Partial Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', 'BOLD Nuisance',...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', gmMask,...
        'MaskThreshold', 0.7,...
        'Parallel', 'gpu',...
        'Tails', 'both'));