function brainData = Initialize(brainData, plotType, plotData, varargin)
%INTIALIZE Initialize the brain data plot environment.
%   INITIALIZE Sets up the environment and important parameters for the plotting of EEG or MRI brain
%   data. 
%
%   WARNING: INITIALIZE is an internal method for brainPlot and is not meant to be called
%   externally.
%
%   Written by Josh Grooms on 20130626
%       20130809:   Updated to work with re-written WINDOWOBJ.
%       20140625:   Removed dependencies on my personal file structure.


%% Initialize
load eegChannels;
inStruct = struct(...
    'Anatomical', [],...
    'AxesColor', 'w',...
    'Channels', {eegChannels},...
    'CLim', [],...
    'Color', 'k',...
    'Colorbar', 'on',...
    'ColorbarLabel', [],...
    'Colormap', jet(256),...
    'Title', [],...
    'Visible', 'on',...
    'XDim', [],...
    'XLabel', [],...
    'XTickLabel', [],...
    'YDim', [],...
    'YLabel', [],...
    'YTickLabel', []);
assignInputs(inStruct, varargin, 'structOnly');

% Setup the plot axes (set units to pixels to control data aspect ratio)
brainData.Axes.Primary = axes(...
    'Units', 'pixels',...
    'Box', 'on',...
    'Color', 'none',...
    'FontSize', 12,...
    'LineWidth', 2,...
    'TickLength', [0 0],...
    'XColor', inStruct.AxesColor,...
    'XLim', [0 1],...
    'XTick', [],...
    'YColor', inStruct.AxesColor,...
    'YLim', [0 1],...
    'YTick', []);

% Setup colorbar properties
if istrue(inStruct.Colorbar)
    inStruct.Colorbar = colorbar('EastOutside');
    set(get(inStruct.Colorbar, 'YLabel'), 'FontSize', 14, 'String', inStruct.ColorbarLabel);
    set(inStruct.Colorbar, 'FontSize', 12);
end

% Determine the type of plot called for & standardize the object tag accordingly
switch lower(plotType)
    case {'bold', 'mri', 'fmri'}
        if isempty(inStruct.YDim)
            inStruct.YDim = 3;
        end
        if isempty(inStruct.XDim)
            inStruct.XDim = 4;
        end
    case {'eeg', 'electrodes'}
        if isempty(inStruct.YDim)
            inStruct.YDim = 3;
        end
        if isempty(inStruct.XDim)
            inStruct.XDim = 2;
        end
end

% Transfer the data being plotted
if isnumeric(plotData)
    inStruct.Data = plotData;
else
    error('Only numeric data arrays may be inputted to brainPlot');
end



%% Transfer Inputs to Object Properties
propNames = fieldnames(inStruct);
for a = 1:length(propNames)
    set(brainData, propNames{a}, inStruct.(propNames{a}));
end