%% 20131029

%% 1914 - Running Correlations between BOLD & BOLD Nuisance Signals
% Setup correlation parameters
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-BOLD Nuisance',...
        'Relation', 'Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', 'BOLD Nuisance',...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', [],...
        'MaskThreshold', [],...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData);
meanCorrData = mean(corrData);
store(meanCorrData);
brainData = plot(meanCorrData);


%% 2000 - Re-Running The Above Correlations, This Time Regressing Nuisance Signals from BOLD Data Prior to Correlation
% I've done this in code, so it won't be visible in the parameters below.
% Setup correlation parameters
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-BOLD Nuisance',...
        'Relation', 'Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', 'BOLD Nuisance',...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', [],...
        'MaskThreshold', [],...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData);
meanCorrData = mean(corrData);
store(meanCorrData);
brainData = plot(meanCorrData);


%% 2045 - Re-Running The Above Correlations, This Time Regressing Nuisance Signals from BOLD Data Prior to Correlation & Including Motion Signals
% I've done this in code, so it won't be visible in the parameters below.
% Setup correlation parameters
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-BOLD Nuisance',...
        'Relation', 'Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', 'BOLD Nuisance',...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', [],...
        'MaskThreshold', [],...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData);
meanCorrData = mean(corrData);
store(meanCorrData);
brainData = plot(meanCorrData, 'CLim', [-3 3]);