function a_powerSpectra_EEG(fileStruct, paramStruct)

%% Initialize the Power Spectra Generation Parameters
load masterStructs;
paramStruct.powerSpectra.EEG = struct(...
    'subjects', [paramStruct.general.subjects],...
    'scans', {paramStruct.general.scans},...
    'electrodes', {{'FPZ' 'P8'}},...
    'lengthSegment', 60000,...
    'pctOverlap', 99.5,...
    'rangeFreqs', [0:0.0001:0.1],...
    'visibleFigs', 'off',...
    'comments', 'For publication: Select EEG channels power spectra');

fileStruct.analysis.powerSpectra.EEG = struct(...
    'eegDataFile', [fileStruct.paths.MAT_files '\EEG\eegData_raw.mat'],...
    'savePathData', [fileStruct.paths.MAT_files '\EEG'],...
    'savePathImage', [fileStruct.paths.analyses '\Power Spectra\EEG\Raw'],...
    'saveID', '20130120',...
    'saveTag', 'raw');

save(fileStruct.files.masterStructs, 'fileStruct', 'paramStruct');

%% Generate & Image the EEG Power Spectra
% Generate the power spectra
ar_powerSpectra_EEG(fileStruct, paramStruct);

% Average together the power spectra
% ara_powerSpectra_EEG(fileStruct, paramStruct);

% Image the power spectra
ai_powerSpectra_EEG(fileStruct, paramStruct);