function a_xcorr_EEG_IC
%% Initialize
load masterStructs.mat;

% Change parameter structure values
paramStruct.xcorr.EEG_IC = struct(...
    'subjects', [paramStruct.general.subjects],...
    'scans', {paramStruct.general.scans},...
    'shiftsTime', [-50:2:50],...
    'imageShifts', [-16:2:16],...
    'alphaVal', 0.05,...
    'imageSingleSubjects', false,...
    'visibleFigs', 'off',...
    'parallelSwitch', false,...
    'comments', 'For publication: (DC-EEG)-IC Cross-Correlation (Thresholding at alpha = 0.05)');

% Change file structure values
fileStruct.analysis.xcorr.EEG_IC = struct(...
    'eegDataFile', [fileStruct.paths.MAT_files '\EEG\eegData_dc.mat'],...
    'icDataFile', [fileStruct.paths.MAT_files '\BOLD\timeCourses_RSN.mat'],...
    'savePathData', [fileStruct.paths.MAT_files '\xcorr'],...
    'savePathImage', [fileStruct.paths.analyses '\Cross-Correlation\EEG-IC\EEG GR\Five Pct Alpha\Montage'],...
    'saveID', '20130117',...
    'saveTag', 'dcGR');
save(fileStruct.files.masterStructs, 'fileStruct', 'paramStruct')


%% Run the Analysis    
% Cross-correlate EEG-IC time courses
% arx_realEI(fileStruct, paramStruct);

% Generate a null distribution for significance testing
% arx_nullEI(fileStruct, paramStruct);

% Average together cross-correlation & null data to reduce data size
% ara_corrEI(fileStruct, paramStruct);

% Bootstrap the data for significance
% arb_corrEI(fileStruct, paramStruct);

% Image the data
ai_corrEI(fileStruct, paramStruct);
