%% 20131028

%% 0916 - RSN-EEG Correlations Using EEG CSR
% Setup correlation parameters
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false true],...
        'Modalities', 'RSN-EEG',...
        'Relation', 'Partial Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', 'BOLD Nuisance',...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', {{[1 2] [1 2] [1 2] [1 2] [1 2] [1 2] [1 2] [1 2]}},...      % <--- No ICA time courses for subject 6 scan 3
        'Subjects', [1:8],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', [],...
        'MaskThreshold', [],...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData)
meanCorrData = mean(corrData);
store(meanCorrData, 'Name', 'meanPartialCorrObject_RS_RSN-EEG_dcCSRZ_20131028', 'varName', 'meanCorrData');
clear corrData


%% 1622 - Threshold the Data
load meanPartialCorrObject_RS_RSN-EEG_dcCSRZ_20131028
threshold(meanCorrData);
store(meanCorrData, 'Name', 'meanPartialCorrObject_RS_RSN-EEG_dcCSRZ_20131028', 'varName', 'meanCorrData');
brainData = plot(meanCorrData, 'Thresholding', 'on');


%% 1856 - Testing out how correlations look if I don't flip around the ICA time courses
% Setup correlation parameters
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false true],...
        'Modalities', 'RSN-EEG',...
        'Relation', 'Partial Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', 'BOLD Nuisance',...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', {{[1 2] [1 2] [1 2] [1 2] [1 2] [1 2] [1 2] [1 2]}},...      % <--- No ICA time courses for subject 6 scan 3
        'Subjects', [1:8],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', [],...
        'MaskThreshold', [],...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
meanCorrData = mean(corrData);
brainData = plot(meanCorrData);

% Results indicate that reversing the time courses (as I have been doing throughout the past) is the correct way to do
% it. Can't figure out why GIFT stores them this way, but even walking through their code reveals that the these
% reconstructed signals are reversed at some point.