classdef Today < hgsetget
% TODAY - A static class containing current date information and Today Script utility functions.    
    
%% CHANGELOG
%   Written by Josh Grooms on 20141015
    


    %% Properties (Defined as Static Methods)
    
    methods (Static)
        
        function D = Date
            % Gets the current date string in the format YYYYMMDD.
            D = datestr(now, 'yyyymmdd');
        end
        function T = Time
            % Gets the current time string in the 24-hour format HHMM.
            T = datestr(now, 'HHMM');
        end
        function P = ScriptPath
            % Gets the path to the folder containing Today Scripts.
            P = Paths.TodayScripts;
        end
        function P = DataPath
            % Gets the path to the repository for all data generated by Today Scripts.
            P = Paths.TodayData;
        end
        
    end
    
    
    
    
    %% Utility Methods
    
    methods (Static)

        function CreateScript()
            % CREATESCRIPT - Creates a new script to serve as a record of daily activities.
            
            date = Today.Date;
            time = Today.Time;
            script = File([Today.ScriptPath '/' date '.m']);
            
            assert(~script.Exists, 'A Today Script with today''s date already exists.');
            
            script.Open('w');
            script.Write(...
                ['%%%% %s \n'...
                 '\n'...
                 '\n'...
                 '%%%% %s - \n'...
                 '%% Today''s parameters\n'...
                 'timeStamp = ''%s'';\n'...
                 'analysisStamp = '''';\n'...
                 'dataSaveName = ''%s/%s - '';\n'...
                 '\n'...
                 '%% Get references to infraslow BOLD & EEG data sets\n'...
                 'boldFiles = get(Paths, ''InfraslowBOLD'');\n'...
                 'eegFiles = get(Paths, ''InfraslowEEG'');\n'],...
                 date,...
                 time,...
                 [date time],...
                 Today.DataPath.ToString(),...
                 [date time]);
            
             script.Close();
             script.Edit();
        end

    end
    
    
    
    
    
end