function dataStruct = ToStruct(dataObject)
%TOSTRUCT - Converts human data objects into data structures.
%   This function is used to convert data objects into data structures. Structures are a value-type in MATLAB and as
%   such are often easier and more intuitive to deal with in this language. Additionally, they offer a lot more
%   flexibility in terms of dynamic field creation and removal.
%
%   However, there are downsides to this conversion. While structures appear not to suffer from the code bload that
%   classes can have, most of the quality control benefits inherent to classes are lost. Examples include: type-safe
%   methods, subclassing, resticted access to fields/methods, and validation of field modifications. Also, as a
%   reference-type, the correct use of classes can eliminate some significant computational overhead that is incurred
%   when using a structure (this is especially apparent for large data sets).
%
%   This method exists so that the user may freely work with a human data set without any restrictions or the need to
%   work with the specialized class methods. 
%
%   SYNTAX:
%   dataStruct = ToStruct(dataObject)
%
%   OUTPUT:
%   dataStruct:     STRUCT
%                   A value-type human data structure in exactly the same apparent format as the inputted data object.
%                   This structure may be editted freely but can no longer be used with any of the methods that are
%                   associated with the original object's class.
%
%   INPUT:
%   dataObject:     HUMANOBJ
%                   A reference-type human data object that is typically generated by preprocessing raw data.



%% CHANGELOG
%   Written by Josh Grooms on 20140711


%% Convert Data Objects into Data Structures
% Initialize the output data structure
dataStruct(numel(dataObject)) = struct();

% Transfer object properties into structure fields
propNames = properties(dataObject(1));
for a = 1:numel(dataObject)
    for b = 1:length(propNames)
        dataStruct(a).(propNames{b}) = dataObject(a).(propNames{b});
    end
end

% Reshape the data structure into the same dimensionality & ordering as the object
dataStruct = reshape(dataStruct, size(dataObject));