function varargout = updateFileStruct(varargin)
%UPDATEFILESTRUCT Updates the file structure.
%   This function lists many of the essential fields of fileStruct that is used throughout numerous functions. Each
%   entry is listed twice (once for the home and again for the office computer) to facilitate easy conversion of the
%   structure depending user location. This function also automatically saves the file structure after the update,
%   overwriting the previous version.
%
%   SYNTAX: 
%   updateFileStruct(location)
%   fileStruct = updateFileStruct(fileStruct, location)
%
%   OUTPUT: 
%   fileStruct:     The updated file structure.
%
%   INPUT: 
%   fileStruct:     The file structure with paths that require updating.
%
%   OPTIONAL INPUT
%   location:       A string representing the the computer that the code is being run on. 
%                   DEFAULT: 'home' 
%                   OPTIONS:
%                       'home'      My home personal desktop computer.
%
%                       'office'    My workstation in my lab's office.

%% CHANGELOG
%   Written by Josh Grooms
%       20130604:   Updated to allow quick changing of file structure between home and office computers. Also wrote a 
%                   help & reference section.
%       20130611:   Added "Results" field to file structure for saving output images.
%       20130703:   Added "Desktop" field to path structure for quick navigation to temporary files.
%       20130711:   Updated path separator to forward slash for ease of conversion to Linux file systems. Added Brainiac 
%                   to the possible file structure update branches.
%       20130728:   Updated the "Results" field back to my local hard drive (Bitcasa is causing problems)
%       20130809:   Added "tablet" computer paths. Added a path to data objects for lab computer.
%       20130919:   Put fileStruct path fields in alphabetical order. Added "Today Scripts" folder path to the file 
%                   structure.
%       20130920:   Added raw data path to office computer file structure.
%       20131115:   Removed the version flag in the save command for the structures. This threw warnings in R2013b.
%                   Updated documentation to conform to recent standards.
%       20140501:   Updated function to allow outputting nothing and accepting a variable number of
%                   inputs. This allows the function to load the master structure set, make changes to the file structure,
%                   and save it without having to pre-load the file structure with paths from
%                   another computer.
%       20140619:   Added a path to a new dumping ground for data generated from Today Scripts. 



%% Initialize
% Fill in variables from user inputs
if nargin == 1 && isstruct(varargin{1})
    fileStruct = varargin{1};
    location = 'home';
elseif nargin == 1 && ischar(varargin{1})
    location = varargin{1};
    load masterStructs;
else
    fileStruct = varargin{1};
    location = varargin{2};
end


%% Change File Structure
switch lower(location)
    % Home computer paths
    case {'home', 'desktop'}
        fileStruct.Paths = struct(...
            'DataObjects', 'E:/Graduate Studies/Lab Work/Data Sets/Data Objects',...
            'DataStructs', 'E:/Graduate Studies/Lab Work/Data Sets/MAT Files',...        
            'Desktop', 'C:/Users/Josh/Desktop',...
            'Globals', 'C:/Users/Josh/Dropbox/Globals',...
            'Main', 'C:/Users/Josh/Dropbox/svnSandbox',...
            'Preprocessed', 'E:/Graduate Studies/Lab Work/Data Sets/Data Objects/Preprocessed',...
            'Raw', 'E:/Graduate Studies/Lab Work/Data Sets/Raw Data',...
            'Results', 'E:/Graduate Studies/Lab Work/Results',...
            'TimeCourses', 'E:/Graduate Studies/Lab Work/Data Sets/ICA Results/Time Course Files',...
            'Today', 'C:/Users/Josh/Dropbox/svnSandbox/Today Scripts',...
            'TodayData', 'I:/Research/Today Data');

        fileStruct.Files = struct(...
            'MNI',  'C:/Users/Josh/Dropbox/Globals/MNI/template/T1.nii',...
            'MasterStructs', 'C:/Users/Josh/Dropbox/svnSandbox/Structures/masterStructs.mat',...
            'Segments', struct(...
                'CSF', 'C:/Users/Josh/Dropbox/Globals/MNI/segments/csf.nii',...
                'Gray', 'C:/Users/Josh/Dropbox/Globals/MNI/segments/grey.nii',...
                'White', 'C:/Users/Josh/Dropbox/Globals/MNI/segments/white.nii'));

    % Tablet paths
    case {'surface', 'tablet'}
        fileStruct.Paths = struct(...
            'DataObjects', 'D:/Lab Work/Data Sets/Data Objects',...
            'DataStructs', [],...
            'Desktop', 'C:/Users/Josh/Desktop',...
            'Globals', 'C:/Users/Josh/Dropbox/Globals',...
            'Main', 'C:/Users/Josh/Dropbox/svnSandbox',...
            'Preprocessed', [],...
            'Raw', [],...
            'Results', [],...
            'TimeCourses', [],...
            'Today', 'C:/Users/Josh/Dropbox/svnSandbox/Today Scripts',...
            'TodayData', 'D:/Lab Work/Data Sets/Today Data');

        fileStruct.Files = struct(...
            'MNI',  'C:/Users/Josh/Dropbox/Globals/MNI/template/T1.nii',...
            'MasterStructs', 'C:/Users/Josh/Dropbox/svnSandbox/Structures/masterStructs.mat',...
            'Segments', struct(...
                'CSF', 'C:/Users/Josh/Dropbox/Globals/MNI/segments/csf.nii',...
                'Gray', 'C:/Users/Josh/Dropbox/Globals/MNI/segments/grey.nii',...
                'White', 'C:/Users/Josh/Dropbox/Globals/MNI/segments/white.nii'));

    % Office workstation paths
    case {'lab', 'work', 'office'}
        fileStruct.Paths = struct(...
            'DataObjects', 'D:/Data Objects',...
            'DataStructs', [],...
            'Desktop', 'C:/Users/jgrooms/Desktop',...
            'Globals', 'C:/Users/jgrooms/Dropbox/Globals',...
            'Main', 'C:/Users/jgrooms/Dropbox/svnSandbox/',...
            'Preprocessed', [],...
            'Raw', [],...
            'TimeCourses', [],...
            'Today', 'C:/Users/jgrooms/Dropbox/svnSandbox/Today Scripts',...
            'TodayData', 'I:/Research/Today Data');

        fileStruct.Files = struct(...
            'MNI',  'C:/Users/jgrooms/Dropbox/Globals/MNI/template/T1.nii',...
            'MasterStructs', 'C:/Users/jgrooms/Dropbox/svnSandbox/Structures/masterStructs.mat',...
            'Segments', struct(...
                'CSF', 'C:/Users/jgrooms/Dropbox/Globals/MNI/segments/csf.nii',...
                'Gray', 'C:/Users/jgrooms/Dropbox/Globals/MNI/segments/grey.nii',...
                'White', 'C:/Users/jgrooms/Dropbox/Globals/MNI/segments/white.nii'));
            
    % Brainiac Linux paths
    case {'brainiac', 'labserver', 'server'}
        fileStruct.Paths = struct(...
            'Desktop', 'C:/Users/jgrooms/Desktop',...
            'Globals', '/shella-lab/Josh/Globals',...
            'Main', '/shella-lab/Josh',...
            'Raw', '/shella-lab/Josh/Data/Raw',...
            'Preprocessed', '/shella-lab/Josh/Data/Objects/Preprocessed',...
            'DataStructs', [],...
            'TimeCourses', [],...
            'DataObjects', '/shella-lab/Josh/Data/Objects');

        fileStruct.Files = struct(...
            'MNI',  '/shella-lab/Josh/Globals/MNI/template/T1.nii',...
            'MasterStructs', '/shella-lab/Josh/Structures/masterStructs.mat',...
            'Segments', struct(...
                'CSF', '/shella-lab/Josh/Globals/MNI/segments/csf.nii',...
                'Gray', '/shella-lab/Josh/Globals/MNI/segments/grey.nii',...
                'White', '/shella-lab/Josh/Globals/MNI/segments/white.nii'));

end

% Save the updated file structure
save(fileStruct.Files.MasterStructs, 'fileStruct', '-append')
assignOutputs(nargout, fileStruct);

    