function a_xcorr_EEG_BOLD
%% Initialize the Parameters for Analysis
load masterStructs
paramStruct.xcorr.EEG_BOLD = struct(...
    'subjects', [paramStruct.general.subjects],...
    'scans', {paramStruct.general.scans},...
    'shiftsTime', [-20:2:20],...
    'electrodes', {{'FPZ' 'P8'}},...
    'imageSlices', [48:2:64],...
    'imageShifts', (-20:4:20),...
    'parallelSwitch', true,...
    'alphaVal', 0.01,...
    'visibleFigs', 'off',...
    'imageSingleSubjects', false,...
    'comments', 'For publication: FPZ & P8 GR DC EEG Cross-Correlation with BOLD (Alpha = 0.01)');

% Change relevant values in the file structure
fileStruct.analysis.xcorr.EEG_BOLD = struct(...
    'eegDataFile', [fileStruct.paths.MAT_files '\EEG\eegData_dcGR_20130120.mat'],...
    'boldDataPath', [fileStruct.paths.MAT_files '\BOLD'],...
    'savePathData', [fileStruct.paths.MAT_files '\xcorr'],...
    'savePathImage', [fileStruct.paths.analyses '\Cross-Correlation\EEG-BOLD\GR EEG\One Pct Alpha\Montage'],...
    'saveTag', 'dcGR',...
    'saveID', '20130120');
save(fileStruct.files.masterStructs, 'fileStruct', 'paramStruct')

%% Run the Analysis
% Perform the cross-correlation
% arx_realEB(fileStruct, paramStruct);

% Generate a null distribution of correlation for bootstrapping
% arx_nullEB(fileStruct, paramStruct);

% Average together cross-correlation & null data to reduce data size
% ara_corrEB(fileStruct, paramStruct);

% Bootstrap the data for significance
% arb_corrEB(fileStruct, paramStruct);

% Image the cross-correlations
ai_corrEB(fileStruct, paramStruct);