%% 20140217


%% 2051 - Re-Running BOLD-Global Correlations (Before GSR)
% The earlier analysis on this front (see 20131030) generated correlation mappings between BOLD and the global signal
% when either no control signals had been regressed from the functional data, or all of them had. As such, it's
% impossible to ascribe the changes seen in those images to GSR alone, because any other nuisance parameter that
% correlates with the global signal could have influenced the results. Thus, I need to re-make the before/after images
% such that the only variable is GSR.

% Before global signal regression
load masterStructs
gmMask = load_nii(fileStruct.Files.Segments.Gray); gmMask = gmMask.img;
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-Global',...
        'Relation', 'Partial Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', {{'Motion', 'WM', 'CSF'}},...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', gmMask,...
        'MaskThreshold', 0.7,...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData, 'Name', 'partialCorrData_BOLD-Global_201402172051_preGSR', 'varName', 'corrData');
meanCorrData = mean(corrData);
store(meanCorrData, 'Name', 'meanPartialCorrData_BOLD-Global_201402172051_preGSR', 'varName', 'meanCorrData');
clear corrData;
brainData = plot(meanCorrData, 'CLim', [-3 3]);
store(brainData, 'ext', {'fig', 'png'});







%% 2208 - Now Running BOLD-Global Correlations After GSR is Performed
% After global signal regression
load masterStructs
gmMask = load_nii(fileStruct.Files.Segments.Gray); gmMask = gmMask.img;
ccStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{[0.01 0.08], [0.01 0.08]}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-Global',...
        'Relation', 'Partial Correlation',...
        'ScanState', 'RS'),...
    'Correlation', struct(...
        'Control', {{'Motion', 'Global', 'WM', 'CSF'}},...
        'Channels', [],...
        'Fs', 0.5,...
        'GenerateNull', false,...
        'Mask', [],...
        'MaskThreshold', [],...
        'Scans', [],...
        'Subjects', [],...
        'TimeShifts', [-20:2:20]),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Mask', gmMask,...
        'MaskThreshold', 0.7,...
        'Parallel', 'gpu',...
        'Tails', 'both'));
corrData = corrObj(ccStruct);
store(corrData, 'Name', 'partialCorrData_BOLD-Global_201402172051_GSR', 'varName', 'corrData');
meanCorrData = mean(corrData);
store(meanCorrData, 'Name', 'meanPartialCorrData_BOLD-Global_201402172051_GSR', 'varName', 'meanCorrData');
clear corrData;
brainData = plot(meanCorrData, 'CLim', [-3 3]);
store(brainData, 'ext', {'fig', 'png'});