%% 20140121


%% 0208 - Re-Running BOLD-EEG Partial Coherence (No CSR, GSR)
% Old coherence data didn't investigate all possible CSR/GSR combinations & hadn't delayed some of the control signals
% being regressed. Also, these new coherence plots will be based on newer BOLD-EEG correlation data with these factors
% taken into account. 

% Coherence Parameters
channels = {'AF7', 'FPZ', 'C3', 'PO8', 'PO10'};
cohStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{'fb', 'fb'}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-EEG',...
        'ParentData', [],...
        'Relation', 'Partial Coherence',...
        'Scans', [],...
        'ScanState', 'RS',...
        'Subjects', []),...
    'Coherence', struct(...
        'Channels', [],...
        'Control', 'BOLD Nuisance',...
        'GenerateNull', false,...
        'Masking', struct(...
            'Method', 'Correlation',...
            'File', [],...
            'Image', [],...
            'Shift', 4,...
            'Threshold', 0.9),...
        'NFFT', [],...
        'SegmentOverlap', [],...
        'Window', []),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Parallel', 'gpu',...
        'Tails', 'upper'));
 
 progBar = progress('Computing Partial Coherence Data (GS included in Control)');
 for a = 2:length(channels)
     cohStruct.Coherence.Channels = channels(a);
     cohData = cohObj(cohStruct);
     saveName = ['partialCohObj_RS_BOLD-' channels{a} '_fb_' datestr(now, 'yyyymmdd') '_GSControl'];
     store(cohData, 'Name', saveName, 'varName', 'cohData');
     saveName(1) = upper(saveName(1)); saveName = ['mean' saveName];
     meanCohData = mean(cohData);
     store(meanCohData, 'Name', saveName, 'varName', 'meanCohData');
 end
 
 clear cohData meanCohData
 
%% 0208 - BOLD-EEG Partial Coherence (No CSR, No GSR)
% Now re-run the above analysis without including the BOLD global in the partial coherence control signals.
cohStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{'fb', 'fb'}},...
        'GSR', [false false],...
        'Modalities', 'BOLD-EEG',...
        'ParentData', [],...
        'Relation', 'Partial Coherence',...
        'Scans', [],...
        'ScanState', 'RS',...
        'Subjects', []),...
    'Coherence', struct(...
        'Channels', [],...
        'Control', {{'Motion', 'WM', 'CSF'}},...
        'GenerateNull', false,...
        'Masking', struct(...
            'Method', 'Correlation',...
            'File', [],...
            'Image', [],...
            'Shift', 4,...
            'Threshold', 0.9),...
        'NFFT', [],...
        'SegmentOverlap', [],...
        'Window', []),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Parallel', 'gpu',...
        'Tails', 'upper'));
    
 progBar = progress('Computing Partial Coherence Data (GS not included in Control)');
 for a = 1:length(channels)
     cohStruct.Coherence.Channels = channels(a);
     cohData = cohObj(cohStruct);
     saveName = ['partialCohObj_RS_BOLD-' channels{a} '_fb_' datestr(now, 'yyyymmdd') '_noGSControl'];
     store(cohData, 'Name', saveName, 'varName', 'cohData');
     meanCohData = mean(cohData);
     saveName(1) = upper(saveName(1)); saveName = ['mean' saveName];
     store(meanCohData, 'Name', saveName, 'varName', 'meanCohData');
     update(progBar, a/length(channels));
 end
 close(progBar);
 
 
%% 1049 - Plot the Data Generated Above
load masterStructs
cohFilesGS = get(fileData([fileStruct.Paths.DataObjects '/Partial Coherence'], 'Search', 'mean.*_GSControl'), 'Path');
cohFilesNoGS = get(fileData([fileStruct.Paths.DataObjects '/Partial Coherence'], 'Search', 'mean.*_noGSControl'), 'Path');
imageSavePath = [fileStruct.Paths.Desktop '/Partial Coherence'];
if ~exist(imageSavePath, 'dir'); mkdir(imageSavePath); end;

for a = 1:length(cohFilesGS)
    load(cohFilesGS{a})
    
    channel = fieldnames(meanCohData.Data);
    freqs = meanCohData.Parameters.Coherence.Frequencies;
    
    shadePlot(...
        freqs,...
        meanCohData.Data.(channel{1}).Mean,...
        meanCohData.Data.(channel{1}).SEM,...
        '-k',...
        'Color', 'w');
        
    xlabel('Frequency (Hz)', 'FontSize', 14);
    ylabel('Magnitude Squared Coherence', 'FontSize', 14);
    title(['BOLD-' channel{1} ' Coherence'], 'FontSize', 16);
    
    saveas(gcf, [imageSavePath '/' channel{1} ' GS.png'], 'png');
    saveas(gcf, [imageSavePath '/' channel{1} ' GS.fig'], 'fig');
    close
    
    load(cohFilesNoGS{a})
    
    channel = fieldnames(meanCohData.Data);
    freqs = meanCohData.Parameters.Coherence.Frequencies;
    
    shadePlot(...
        freqs,...
        meanCohData.Data.(channel{1}).Mean,...
        meanCohData.Data.(channel{1}).SEM,...
        '-k',...
        'Color', 'w');
        
    xlabel('Frequency (Hz)', 'FontSize', 14);
    ylabel('Magnitude Squared Coherence', 'FontSize', 14);
    title(['BOLD-' channel{1} ' Coherence'], 'FontSize', 16);
    
    saveas(gcf, [imageSavePath '/' channel{1} ' No GS.png'], 'png');
    saveas(gcf, [imageSavePath '/' channel{1} ' No GS.fig'], 'fig');
    close
end

% Results: very different from old coherence spectra currently still visible in the paper figures outline (back from
% before control signals were being properly regressed & were not delayed appropriately). High peaks still occur at
% roughly the same frequencies, but the distribution of high coherence values is visibly different. Will need to
% threshold these data. The difference between GSR/no GSR is small but does exist. Peaks occur at the same frequency,
% but the morphology of the spectrum waveform is noticeably different.


%% 1112 - BOLD-EEG Partial Coherence (CSR, GSR)
% Coherence Parameters
channels = {'AF7', 'FPZ', 'C3', 'PO8', 'PO10'};
cohStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{'fb', 'fb'}},...
        'GSR', [false true],...
        'Modalities', 'BOLD-EEG',...
        'ParentData', [],...
        'Relation', 'Partial Coherence',...
        'Scans', [],...
        'ScanState', 'RS',...
        'Subjects', []),...
    'Coherence', struct(...
        'Channels', [],...
        'Control', {{'Motion', 'Global', 'WM', 'CSF'}},...
        'GenerateNull', false,...
        'Masking', struct(...
            'Method', 'Correlation',...
            'File', [],...
            'Image', [],...
            'Shift', 4,...
            'Threshold', 0.9),...
        'NFFT', [],...
        'SegmentOverlap', [],...
        'Window', []),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Parallel', 'gpu',...
        'Tails', 'upper'));
    
 progBar = progress('Computing Partial Coherence Data (GS included in Control)');
 for a = 1:length(channels)
     cohStruct.Coherence.Channels = channels(a);
     cohData = cohObj(cohStruct);
     saveName = ['partialCohObj_RS_BOLD-' channels{a} '_fbCSR_' datestr(now, 'yyyymmdd') '_GSControl'];
     store(cohData, 'Name', saveName, 'varName', 'cohData');
     meanCohData = mean(cohData);
     saveName(1) = upper(saveName(1)); saveName = ['mean' saveName];
     store(meanCohData, 'Name', saveName, 'varName', 'meanCohData');
     update(progBar, a/length(channels));
 end
 close(progBar);
 
 
 %% 1210 - Plot the Data Just Generated
load masterStructs
cohFilesGS = get(fileData([fileStruct.Paths.DataObjects '/Partial Coherence'], 'Search', 'mean.*CSR.*_GSControl'), 'Path');
imageSavePath = [fileStruct.Paths.Desktop '/Partial Coherence'];
if ~exist(imageSavePath, 'dir'); mkdir(imageSavePath); end;

for a = 1:length(cohFilesGS)
    load(cohFilesGS{a})
    
    channel = fieldnames(meanCohData.Data);
    freqs = meanCohData.Parameters.Coherence.Frequencies;
    
    shadePlot(...
        freqs,...
        meanCohData.Data.(channel{1}).Mean,...
        meanCohData.Data.(channel{1}).SEM,...
        '-k',...
        'Color', 'w');
        
    xlabel('Frequency (Hz)', 'FontSize', 14);
    ylabel('Magnitude Squared Coherence', 'FontSize', 14);
    title(['BOLD-' channel{1} ' Coherence'], 'FontSize', 16);
    
    saveas(gcf, [imageSavePath '/' channel{1} ' GS.png'], 'png');
    saveas(gcf, [imageSavePath '/' channel{1} ' GS.fig'], 'fig');
    close
end
 
% Results: These look very much like the old results (with both CSR & GSR). It seems that EEG CSR plays the biggest role
% in influencing the morphology of the coherence spectrum. I expect that removing the BOLD global signal from the
% control data will result in nearly (if not completely) identical results to before, because the difference between the
% two is minimal and, from earlier this morning, GSR control seems to have little effect. 


 %% 1216 - BOLD-EEG Partial Coherence (CSR, No GSR)
 % Coherence Parameters
channels = {'AF7', 'FPZ', 'C3', 'PO8', 'PO10'};
cohStruct = struct(...
    'Initialization', struct(...
        'Bandwidth', {{'fb', 'fb'}},...
        'GSR', [false true],...
        'Modalities', 'BOLD-EEG',...
        'ParentData', [],...
        'Relation', 'Partial Coherence',...
        'Scans', [],...
        'ScanState', 'RS',...
        'Subjects', []),...
    'Coherence', struct(...
        'Channels', [],...
        'Control', {{'Motion', 'WM', 'CSF'}},...
        'GenerateNull', false,...
        'Masking', struct(...
            'Method', 'Correlation',...
            'File', [],...
            'Image', [],...
            'Shift', 4,...
            'Threshold', 0.9),...
        'NFFT', [],...
        'SegmentOverlap', [],...
        'Window', []),...
    'Thresholding', struct(...
        'AlphaVal', 0.05,...
        'CDFMethod', 'arbitrary',...
        'FWERMethod', 'sgof',...
        'Parallel', 'gpu',...
        'Tails', 'upper'));
    
 progBar = progress('Computing Partial Coherence Data (GS not included in Control)');
 for a = 1:length(channels)
     cohStruct.Coherence.Channels = channels(a);
     cohData = cohObj(cohStruct);
     saveName = ['partialCohObj_RS_BOLD-' channels{a} '_fbCSR_' datestr(now, 'yyyymmdd') '_noGSControl'];
     store(cohData, 'Name', saveName, 'varName', 'cohData');
     meanCohData = mean(cohData);
     saveName(1) = upper(saveName(1)); saveName = ['mean' saveName];
     store(meanCohData, 'Name', saveName, 'varName', 'meanCohData');
     update(progBar, a/length(channels));
 end
 close(progBar);
 
 
 %% 1705 - Plot the Data Generated Above
 load masterStructs
cohFilesGS = get(fileData([fileStruct.Paths.DataObjects '/Partial Coherence'], 'Search', 'mean.*CSR.*_noGSControl'), 'Path');
imageSavePath = [fileStruct.Paths.Desktop '/Partial Coherence'];
if ~exist(imageSavePath, 'dir'); mkdir(imageSavePath); end;

for a = 1:length(cohFilesGS)
    load(cohFilesGS{a})
    
    channel = fieldnames(meanCohData.Data);
    freqs = meanCohData.Parameters.Coherence.Frequencies;
    
    shadePlot(...
        freqs,...
        meanCohData.Data.(channel{1}).Mean,...
        meanCohData.Data.(channel{1}).SEM,...
        '-k',...
        'Color', 'w');
        
    xlabel('Frequency (Hz)', 'FontSize', 14);
    ylabel('Magnitude Squared Coherence', 'FontSize', 14);
    title(['BOLD-' channel{1} ' Coherence'], 'FontSize', 16);
    
    saveas(gcf, [imageSavePath '/' channel{1} ' No GS.png'], 'png');
    saveas(gcf, [imageSavePath '/' channel{1} ' No GS.fig'], 'fig');
    close
end

% Results: As expected, removing the global signal made little difference.