function visualize(networkData)




% Pull important parameters from the network
szNetwork = size(networkData.Neurons, 1);
firingData = [networkData.Neurons.IsFiring]';
firingMap = reshape(firingData, szNetwork, szNetwork);

% Initialize the network visualization window & axes
if isempty(networkData.Visualization)
    networkData.Visualization = windowObj(...
        'Color', 'k',...
        'Colormap', jet(128),...
        'FigureNumber', 5000,...
        'MenuBar', 'off',...
        'Name', 'Neural Network Visualizer',...
        'NumberTitle', 'off',...
        'Position', 'upper-right',...
        'Resizable', 'off',...
        'Size', 'quarterscreen');
    
    networkData.Visualization.Axes = axes(...
        'CLim', [0 1],...
        'XLim', [0 szNetwork],...
        'XTick', [],...
        'YLim', [0 szNetwork],...
        'YTick', []);
end

% Display an image of the firing data in the window
image(...
    'CData', firingMap,...
    'CDataMapping', 'scaled',...
    'Parent', networkData.Visualization.Axes,...
    'XData', [0 szNetwork],...
    'YData', [0 szNetwork]);
    
drawnow